
services:
  - type: web
    runtime: docker
    name: mai-at-ucsd-inventory
    repo: https://github.com/StarDylan/MAI-at-UCSD-Inventory.git
    rootDir: backend
    envVars:
      - key: DEBUG
        value: 'False'