# Generated by Django 5.2.5 on 2025-09-15 00:58

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('source', models.CharField(max_length=255)),
                ('log_level', models.IntegerField()),
                ('log_level_name', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('args', models.TextField(blank=True, default='')),
                ('module', models.CharField(blank=True, default='', max_length=255)),
                ('function_name', models.CharField(blank=True, default='', max_length=255)),
                ('line_num', models.IntegerField(blank=True, null=True)),
                ('exception', models.TextField(blank=True, default='')),
                ('process', models.IntegerField(blank=True, null=True)),
                ('thread', models.CharField(blank=True, default='', max_length=255)),
                ('thread_name', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'access_log',
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('source', models.CharField(max_length=255)),
                ('log_level', models.IntegerField()),
                ('log_level_name', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('args', models.TextField(blank=True, default='')),
                ('module', models.CharField(blank=True, default='', max_length=255)),
                ('function_name', models.CharField(blank=True, default='', max_length=255)),
                ('line_num', models.IntegerField(blank=True, null=True)),
                ('exception', models.TextField(blank=True, default='')),
                ('process', models.IntegerField(blank=True, null=True)),
                ('thread', models.CharField(blank=True, default='', max_length=255)),
                ('thread_name', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'error_log',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(blank=True, default='', help_text='Product manufacturer or brand name', max_length=255)),
                ('gtin', models.CharField(blank=True, default='', help_text='Global Trade Item Number (GTIN-8, GTIN-12, GTIN-13, or GTIN-14)', max_length=14)),
                ('items_per_box', models.PositiveIntegerField(blank=True, help_text='Number of individual items in a single box/package', null=True)),
                ('cost_per_item', models.DecimalField(blank=True, decimal_places=4, help_text='Cost per individual item', max_digits=10, null=True)),
                ('notes_public', models.TextField(blank=True, default='')),
                ('notes_private', models.TextField(blank=True, default='')),
                ('url', models.URLField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'permissions': [('view_deleteditem', 'Can view deleted items'), ('restore_deleteditem', 'Can restore deleted items'), ('view_internalstockingdetails', 'Can view internal stocking'), ('view_advancedpropertiesitem', 'Can view advanced properties'), ('add_viaspreadsheet_item', 'Can add items via spreadsheet')],
            },
        ),
        migrations.CreateModel(
            name='LatencyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('path', models.CharField(max_length=512)),
                ('time', models.IntegerField(help_text='Latency in milliseconds')),
            ],
            options={
                'db_table': 'latency_log',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Name of the tag (e.g., 'PPE', 'Disposable')", max_length=100)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description of this tag')),
                ('color', models.CharField(blank=True, default='', help_text='Hex color code (optional, inherits from tag group if empty)', max_length=7)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Order for displaying tags within group')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this tag is active')),
            ],
            options={
                'db_table': 'tag',
                'ordering': ['tag_group__sort_order', 'tag_group__name', 'sort_order', 'name'],
                'permissions': [('hide_tag', 'Can hide tags')],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_picture', models.CharField(default='/static/inventory/original_logo_square.png', max_length=255)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'permissions': [('restore_user', 'Can restore user')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('entity_type', models.CharField(db_column='type', editable=False, max_length=50)),
                ('entity_id', models.UUIDField(editable=False)),
                ('event', models.CharField(editable=False, max_length=255)),
                ('before', models.TextField(blank=True, default='', editable=False)),
                ('after', models.TextField(blank=True, default='', editable=False)),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('view_allauditevents', 'Can view all audit events')],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.URLField(help_text='Full-size image URL')),
                ('thumbnail_url', models.URLField(blank=True, default='', help_text='Thumbnail image URL for lists and previews')),
                ('public_id', models.CharField(blank=True, max_length=255, null=True)),
                ('thumbnail_public_id', models.CharField(blank=True, default='', help_text='Cloudinary public ID for thumbnail', max_length=255)),
                ('item', models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inventory.item')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=20)),
                ('address', models.TextField(blank=True, default='')),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_organization_name')],
            },
        ),
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Total weight of all items in the checkout (filled at completion)', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Additional notes for this checkout')),
                ('is_completed', models.BooleanField(default=False)),
                ('is_donation', models.BooleanField(default=True, help_text='Whether this checkout represents a donation (unchecked for internal transfers, sales, etc.)')),
                ('completed_by', models.ForeignKey(blank=True, db_column='completed_by_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_checkouts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(db_column='created_by_id', on_delete=django.db.models.deletion.PROTECT, related_name='created_checkouts', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(db_column='organization_id', help_text='Organization that items are being checked out to', on_delete=django.db.models.deletion.PROTECT, related_name='checkouts', to='inventory.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('complete_checkout', 'Can complete checkout'), ('undo_checkout', 'Can undo completed checkout')],
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('location', models.CharField(help_text='Specific location where this stock is stored', max_length=100)),
                ('gtin', models.CharField(blank=True, default='', help_text='Global Trade Item Number (GTIN-8, GTIN-12, GTIN-13, or GTIN-14)', max_length=14)),
                ('detail', models.CharField(blank=True, default='', help_text='Additional details like size, color, variant, etc.', max_length=255)),
                ('date_received', models.DateField()),
                ('expiration_date', models.DateField(blank=True, help_text='Leave blank for non-perishable items', null=True)),
                ('lot_number', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('surplus_status', models.CharField(choices=[('pending', 'Surplus Needs to Check'), ('wanted', 'Wanted by Surplus'), ('not_wanted', 'Not Wanted by Surplus')], default='pending', help_text='Surplus approval status for this stock item', max_length=20)),
                ('item', models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='inventory.item')),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='inventory.organization')),
            ],
            options={
                'ordering': ['detail', 'expiration_date', 'date_received'],
                'permissions': [('view_surplus_report', 'Can view surplus reports'), ('download_surplus_report', 'Can download surplus reports'), ('upload_surplus_report', 'Can upload surplus reports')],
            },
        ),
        migrations.CreateModel(
            name='CheckOutItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(help_text='Quantity to check out from this stock item')),
                ('notes', models.TextField(blank=True, default='', help_text='Notes specific to this line item')),
                ('checkout', models.ForeignKey(db_column='checkout_id', on_delete=django.db.models.deletion.CASCADE, related_name='checkout_items', to='inventory.checkout')),
                ('stock_item', models.ForeignKey(db_column='stock_item_id', on_delete=django.db.models.deletion.PROTECT, related_name='checkout_items', to='inventory.stockitem')),
            ],
            options={
                'ordering': ['stock_item__item__name', 'stock_item__detail'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags assigned to this item for flexible categorization', related_name='items', to='inventory.tag'),
        ),
        migrations.CreateModel(
            name='TagGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Name of the tag group (e.g., 'Medical Supplies')", max_length=100)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description of this tag group')),
                ('color', models.CharField(default='#6c757d', help_text='Hex color code for visual representation (e.g., #ff0000)', max_length=7)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Order for displaying tag groups')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this tag group is active')),
            ],
            options={
                'db_table': 'tag_group',
                'ordering': ['sort_order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('name',), name='unique_tag_group_name')],
            },
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_group',
            field=models.ForeignKey(help_text='The group this tag belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='tags', to='inventory.taggroup'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('username',), name='unique_user_username'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('email',), name='unique_user_email'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['entity_type', 'id', 'created_at'], name='inventory_a_type_3f2343_idx'),
        ),
        migrations.AddConstraint(
            model_name='checkoutitem',
            constraint=models.UniqueConstraint(fields=('checkout', 'stock_item'), name='unique_checkout_stock_item'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_item_name'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('gtin__gt', '')), fields=('gtin',), name='unique_item_gtin'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_tag_name_global'),
        ),
    ]
