# Generated by Django 5.2.5 on 2025-08-30 01:03

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('source', models.CharField(max_length=255)),
                ('log_level', models.IntegerField()),
                ('log_level_name', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('args', models.TextField(blank=True, default='')),
                ('module', models.CharField(blank=True, default='', max_length=255)),
                ('function_name', models.CharField(blank=True, default='', max_length=255)),
                ('line_num', models.IntegerField(blank=True, null=True)),
                ('exception', models.TextField(blank=True, default='')),
                ('process', models.IntegerField(blank=True, null=True)),
                ('thread', models.CharField(blank=True, default='', max_length=255)),
                ('thread_name', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'access_log',
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('source', models.CharField(max_length=255)),
                ('log_level', models.IntegerField()),
                ('log_level_name', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('args', models.TextField(blank=True, default='')),
                ('module', models.CharField(blank=True, default='', max_length=255)),
                ('function_name', models.CharField(blank=True, default='', max_length=255)),
                ('line_num', models.IntegerField(blank=True, null=True)),
                ('exception', models.TextField(blank=True, default='')),
                ('process', models.IntegerField(blank=True, null=True)),
                ('thread', models.CharField(blank=True, default='', max_length=255)),
                ('thread_name', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'error_log',
            },
        ),
        migrations.CreateModel(
            name='LatencyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('path', models.CharField(max_length=512)),
                ('time', models.IntegerField(help_text='Latency in milliseconds')),
            ],
            options={
                'db_table': 'latency_log',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_picture', models.URLField(default='/static/mai_logo.png')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'permissions': [('restore_user', 'Can restore user')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity_type', models.CharField(db_column='type', editable=False, max_length=50)),
                ('entity_id', models.UUIDField(editable=False)),
                ('event', models.CharField(editable=False, max_length=255)),
                ('before', models.TextField(blank=True, default='', editable=False)),
                ('after', models.TextField(blank=True, default='', editable=False)),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'category',
                'constraints': [models.UniqueConstraint(fields=('name',), name='unique_active_category_name')],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, default='', max_length=100)),
                ('quantity_active', models.PositiveIntegerField(default=0)),
                ('notes_public', models.TextField(blank=True, default='')),
                ('notes_private', models.TextField(blank=True, default='')),
                ('url', models.URLField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.category')),
            ],
            options={
                'permissions': [('view_deleteditem', 'Can view deleted items'), ('restore_deleteditem', 'Can restore deleted items'), ('view_internalstockingdetails', 'Can view internal stocking'), ('view_advancedpropertiesitem', 'Can view advanced properties')],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.URLField()),
                ('public_id', models.CharField(blank=True, max_length=255, null=True)),
                ('item', models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inventory.item')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcategories', to='inventory.category')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='subcategory',
            field=models.ForeignKey(blank=True, db_column='subcategory_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.subcategory'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('username',), name='unique_user_username'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('email',), name='unique_user_email'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['entity_type', 'id', 'created_at'], name='inventory_a_type_3f2343_idx'),
        ),
        migrations.AddConstraint(
            model_name='subcategory',
            constraint=models.UniqueConstraint(fields=('name', 'category'), name='unique_active_subcategory_name'),
        ),
    ]
