# Generated by Django 5.2.5 on 2025-09-03 21:54

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='item',
            name='unique_item_name',
        ),
        migrations.RemoveConstraint(
            model_name='organization',
            name='unique_organization_name',
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_item_name'),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_organization_name'),
        ),
    ]
