# Generated by Django 5.2.5 on 2025-08-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('name',), name='unique_active_category_name'),
        ),
        migrations.AddConstraint(
            model_name='subcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('name', 'category'), name='unique_active_subcategory_name'),
        ),
    ]
