# Generated by Django 5.2.5 on 2025-09-14 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['tag_group__sort_order', 'tag_group__name', 'sort_order', 'name'], 'permissions': [('hide_tag', 'Can hide tags')]},
        ),
    ]
