# Generated by Django 5.2.5 on 2025-09-15 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessLog',
        ),
        migrations.DeleteModel(
            name='ErrorLog',
        ),
        migrations.DeleteModel(
            name='LatencyLog',
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='event',
            field=models.TextField(editable=False),
        ),
    ]
