# Generated by Django 5.2.5 on 2025-09-15 03:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_delete_accesslog_delete_errorlog_delete_latencylog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='url',
            field=models.TextField(blank=True, default='', validators=[django.core.validators.URLValidator()]),
        ),
    ]
