# Generated by Django 5.2.5 on 2025-09-14 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_tag_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stockitem',
            name='unique_stockitem_gtin',
        ),
    ]
