# Generated by Django 5.2.5 on 2025-09-04 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_add_gtin_to_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='location',
            field=models.CharField(help_text='Specific location where this stock is stored', max_length=100),
        ),
    ]
