# Generated by Django 5.2.5 on 2024-12-02 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_organization_stockitem_item_unique_item_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockitem',
            name='is_active',
        ),
    ]