# Generated by Django 5.2.5 on 2025-08-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_user_options_user_unique_user_username_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='audit_type_990a2b_idx',
            old_name='audit_type_71e98b_idx',
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
