# Generated by Django 5.2.5 on 2025-09-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_item_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp of last update to this item or its related data'),
        ),
    ]
