# Generated by Django 5.2.6 on 2025-01-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_stockitem_gtin_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumbnail_url',
            field=models.URLField(blank=True, default='', help_text='Thumbnail image URL for lists and previews'),
        ),
        migrations.AddField(
            model_name='image',
            name='thumbnail_public_id',
            field=models.CharField(blank=True, default='', help_text='Cloudinary public ID for thumbnail', max_length=255),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.URLField(help_text='Full-size image URL'),
        ),
    ]