# Generated by Django 5.2.5 on 2025-09-02 18:04

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_item_quantity_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockitem',
            options={'permissions': [('view_stockitem_details', 'Can view stock item details')]},
        ),
        migrations.AlterModelManagers(
            name='item',
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameIndex(
            model_name='stockitem',
            new_name='inventory_s_item_id_b15f7a_idx',
            old_name='inventory_st_item_id_e850b3_idx',
        ),
        migrations.RenameIndex(
            model_name='stockitem',
            new_name='inventory_s_organiz_6913e9_idx',
            old_name='inventory_st_organiz_62b53d_idx',
        ),
        migrations.AddField(
            model_name='stockitem',
            name='location',
            field=models.CharField(blank=True, default='', help_text='Specific location where this stock is stored', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_item_name'),
        ),
    ]
