# Generated by Django 5.2.5 on 2025-09-21 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_item_last_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['tag_group__sort_order', 'tag_group__name', 'name'], 'permissions': [('hide_tag', 'Can hide tags')]},
        ),
        migrations.RemoveField(
            model_name='tag',
            name='sort_order',
        ),
    ]
