# Generated by Django 5.2.5 on 2025-09-20 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_item_last_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'permissions': [('view_deleteditem', 'Can view deleted items'), ('restore_deleteditem', 'Can restore deleted items'), ('view_internalstockingdetails', 'Can view internal stocking'), ('view_advancedpropertiesitem', 'Can view advanced properties'), ('add_viaspreadsheet_item', 'Can add items via spreadsheet'), ('bulkedit_item', 'Can bulk edit items via spreadsheet')]},
        ),
    ]
