# Generated by Django 5.2.5 on 2025-09-21 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_tag_options_remove_tag_sort_order'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='item',
            name='unique_item_name',
        ),
        migrations.RemoveConstraint(
            model_name='item',
            name='unique_item_gtin',
        ),
    ]
