# Generated by Django 5.2.5 on 2025-09-05 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_add_stockitem_delete_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockitem',
            options={'ordering': ['detail', 'expiration_date', 'date_received']},
        ),
    ]
