# Generated by Django 5.2.5 on 2026-01-09 23:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_item_unique_item_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Name of the location (e.g., 'Warehouse A', 'Shelf B2')", max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this location is active and can be used for new stock')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'location',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='location',
            field=models.CharField(help_text='Specific location where this stock is stored (deprecated, will be removed)', max_length=100),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='location_new',
            field=models.ForeignKey(blank=True, help_text='Specific location where this stock is stored', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='inventory.location'),
        ),
    ]
