# Generated by Django 5.2.6 on 2025-09-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_stockitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='manufacturer',
            field=models.CharField(blank=True, default='', help_text='Product manufacturer or brand name', max_length=255),
        ),
    ]
