# Generated by Django 5.2.5 on 2026-01-09 23:06

from django.db import migrations


def migrate_locations(apps, schema_editor):
    """
    Migrate existing location strings from StockItem to the new Location model.
    Creates Location objects from unique location strings and updates StockItem foreign keys.
    """
    StockItem = apps.get_model('inventory', 'StockItem')
    Location = apps.get_model('inventory', 'Location')
    
    # Create locations from existing stock item locations
    location_map = {}
    unique_locations = StockItem.objects.exclude(location='').values_list('location', flat=True).distinct()
    
    for location_name in unique_locations:
        if location_name and location_name.strip():  # Skip empty strings
            location, created = Location.objects.get_or_create(
                name=location_name.strip(),
                defaults={'is_active': True}
            )
            location_map[location_name.strip()] = location
            if created:
                print(f"Created location: {location.name}")
    
    # Update stock items with the new foreign key
    updated_count = 0
    for stock_item in StockItem.objects.exclude(location=''):
        if stock_item.location and stock_item.location.strip() in location_map:
            stock_item.location_new = location_map[stock_item.location.strip()]
            stock_item.save(update_fields=['location_new'])
            updated_count += 1
    
    print(f"Migrated {updated_count} stock items to use new Location foreign keys")
    print(f"Created {len(location_map)} unique locations")


def reverse_migrate_locations(apps, schema_editor):
    """
    Reverse migration: Copy location names back from Location FK to location string field.
    """
    StockItem = apps.get_model('inventory', 'StockItem')
    
    updated_count = 0
    for stock_item in StockItem.objects.filter(location_new__isnull=False):
        stock_item.location = stock_item.location_new.name
        stock_item.save(update_fields=['location'])
        updated_count += 1
    
    print(f"Reversed {updated_count} stock items back to string locations")


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_add_location_model'),
    ]

    operations = [
        migrations.RunPython(migrate_locations, reverse_migrate_locations),
    ]
