# Generated by Django 5.2.5 on 2025-09-06 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_add_bulk_checkout_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutitem',
            name='cost_per_item',
        ),
        migrations.AddField(
            model_name='item',
            name='cost_per_item',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost per individual item', max_digits=10, null=True),
        ),
    ]
