# Generated by Django 5.2.5 on 2025-09-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_add_cost_per_item_to_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cost_per_item',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Cost per individual item', max_digits=10, null=True),
        ),
    ]
