# Generated by Django 5.2.5 on 2025-09-06 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_item_cost_per_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkout',
            options={'ordering': ['-created_at'], 'permissions': [('complete_checkout', 'Can complete checkout'), ('undo_checkout', 'Can undo completed checkout')]},
        ),
    ]
