# Generated by Django 5.2.5 on 2025-09-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_checkout_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='surplus_status',
            field=models.CharField(choices=[('pending', 'Surplus Needs to Check'), ('wanted', 'Wanted by Surplus'), ('not_wanted', 'Not Wanted by Surplus')], default='pending', help_text='Surplus approval status for this stock item', max_length=20),
        ),
    ]
