# Generated by Django 5.2.5 on 2025-09-08 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_add_surplus_status_to_stockitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockitem',
            options={'ordering': ['detail', 'expiration_date', 'date_received'], 'permissions': [('view_surplus_report', 'Can view surplus reports'), ('download_surplus_report', 'Can download surplus reports'), ('upload_surplus_report', 'Can upload surplus reports')]},
        ),
    ]
