# Generated by Django 5.2.5 on 2025-09-08 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_stockitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='is_donation',
            field=models.BooleanField(default=True, help_text='Whether this checkout represents a donation (unchecked for internal transfers, sales, etc.)'),
        ),
    ]
