# Generated by Django 5.2.5 on 2025-09-10 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_add_is_donation_to_checkout'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditevent',
            options={'permissions': [('view_allauditevents', 'Can view all audit events')]},
        ),
    ]
