# Generated by Django 5.2.5 on 2025-09-10 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_auditevent_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'permissions': [('view_deleteditem', 'Can view deleted items'), ('restore_deleteditem', 'Can restore deleted items'), ('view_internalstockingdetails', 'Can view internal stocking'), ('view_advancedpropertiesitem', 'Can view advanced properties'), ('add_viaspreadsheet_item', 'Can add items via spreadsheet')]},
        ),
    ]
