# Generated by Django 5.2.5 on 2025-09-12 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_alter_item_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
