# Generated by Django 5.2.5 on 2025-09-13 22:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_alter_auditevent_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Name of the tag (e.g., 'PPE', 'Disposable')", max_length=100)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description of this tag')),
                ('color', models.CharField(blank=True, default='', help_text='Hex color code (optional, inherits from tag group if empty)', max_length=7)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Order for displaying tags within group')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this tag is active')),
            ],
            options={
                'db_table': 'tag',
                'ordering': ['tag_group__sort_order', 'tag_group__name', 'sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags assigned to this item for flexible categorization', related_name='items', to='inventory.tag'),
        ),
        migrations.CreateModel(
            name='TagGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Name of the tag group (e.g., 'Medical Supplies')", max_length=100)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description of this tag group')),
                ('color', models.CharField(default='#6c757d', help_text='Hex color code for visual representation (e.g., #ff0000)', max_length=7)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Order for displaying tag groups')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this tag group is active')),
            ],
            options={
                'db_table': 'tag_group',
                'ordering': ['sort_order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('name',), name='unique_tag_group_name')],
            },
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_group',
            field=models.ForeignKey(help_text='The group this tag belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='tags', to='inventory.taggroup'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('name', 'tag_group'), name='unique_tag_name_per_group'),
        ),
    ]
