# Generated by Django 5.2.5 on 2025-09-13 22:12

from django.db import migrations


def convert_categories_to_tags(apps, schema_editor):
    """
    Convert existing categories and subcategories to the new tag system.
    
    This migration:
    1. Creates tag groups from categories
    2. Creates tags from subcategories (or category names if no subcategories)
    3. Assigns appropriate tags to items based on their category/subcategory
    """
    # Get model classes from the migration state
    Category = apps.get_model('inventory', 'Category')
    Subcategory = apps.get_model('inventory', 'Subcategory')
    Item = apps.get_model('inventory', 'Item')
    TagGroup = apps.get_model('inventory', 'TagGroup')
    Tag = apps.get_model('inventory', 'Tag')
    
    # Color palette for tag groups
    tag_group_colors = [
        '#007bff',  # Blue
        '#28a745',  # Green
        '#dc3545',  # Red
        '#ffc107',  # Yellow
        '#6f42c1',  # Purple
        '#fd7e14',  # Orange
        '#20c997',  # Teal
        '#6c757d',  # Gray
        '#e83e8c',  # Pink
        '#17a2b8',  # Cyan
    ]
    
    category_to_tag_group = {}
    sort_order = 0
    
    print("Converting categories and subcategories to tags...")
    
    # Process each category
    for category in Category.objects.all():
        # Create a tag group for each category
        color = tag_group_colors[sort_order % len(tag_group_colors)]
        tag_group = TagGroup.objects.create(
            name=category.name,
            description=f"Tag group converted from category: {category.name}",
            color=color,
            sort_order=sort_order
        )
        category_to_tag_group[category.id] = tag_group
        sort_order += 1
        
        subcategories = Subcategory.objects.filter(category=category)
        
        if subcategories.exists():
            # Create tags for each subcategory
            tag_sort_order = 0
            for subcategory in subcategories:
                tag = Tag.objects.create(
                    name=subcategory.name,
                    description=f"Tag converted from subcategory: {category.name} > {subcategory.name}",
                    tag_group=tag_group,
                    sort_order=tag_sort_order
                )
                tag_sort_order += 1
                
                # Assign this tag to all items in this subcategory
                items_in_subcategory = Item.objects.filter(subcategory=subcategory)
                for item in items_in_subcategory:
                    item.tags.add(tag)
                    
                print(f"  Created tag '{tag.name}' in group '{tag_group.name}' ({items_in_subcategory.count()} items)")
        else:
            # No subcategories, create a tag with the same name as the category
            tag = Tag.objects.create(
                name=category.name,
                description=f"Tag converted from category: {category.name}",
                tag_group=tag_group,
                sort_order=0
            )
            
            # Assign this tag to all items in this category (with no subcategory)
            items_in_category = Item.objects.filter(category=category, subcategory__isnull=True)
            for item in items_in_category:
                item.tags.add(tag)
                
            print(f"  Created tag '{tag.name}' in group '{tag_group.name}' ({items_in_category.count()} items)")
    
    print(f"Migration completed. Created {TagGroup.objects.count()} tag groups and {Tag.objects.count()} tags.")


def reverse_conversion(apps, schema_editor):
    """
    Reverse the migration by removing all tags and tag groups.
    Note: This will lose any tags that were added after the conversion.
    """
    TagGroup = apps.get_model('inventory', 'TagGroup')
    Tag = apps.get_model('inventory', 'Tag')
    
    print("Reversing tag conversion...")
    
    # Clear all tag assignments from items
    Item = apps.get_model('inventory', 'Item')
    for item in Item.objects.all():
        item.tags.clear()
    
    # Delete all tags and tag groups
    Tag.objects.all().delete()
    TagGroup.objects.all().delete()
    
    print("Tag conversion reversed.")


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_add_tag_system'),
    ]

    operations = [
        migrations.RunPython(convert_categories_to_tags, reverse_conversion),
    ]
