# Generated by Django 5.2.5 on 2025-09-14 01:01

from django.db import migrations, models
import django.db.models.deletion


def set_default_category(apps, schema_editor):
    """
    Get or create a default category for items that need one during transition.
    """
    Category = apps.get_model('inventory', 'Category')
    Item = apps.get_model('inventory', 'Item')
    
    # Try to get the most common category, or create a default one
    default_category, created = Category.objects.get_or_create(
        name='Uncategorized',
        defaults={'name': 'Uncategorized'}
    )
    
    if created:
        print(f"Created default category: {default_category.name}")
    
    # Update any items that might not have a category (shouldn't happen but safety first)
    items_without_category = Item.objects.filter(category__isnull=True)
    if items_without_category.exists():
        items_without_category.update(category=default_category)
        print(f"Updated {items_without_category.count()} items to use default category")


def reverse_default_category(apps, schema_editor):
    """
    Reverse migration - remove the default category if it was created
    """
    Category = apps.get_model('inventory', 'Category')
    try:
        default_category = Category.objects.get(name='Uncategorized')
        # Don't delete if it has items assigned
        if not default_category.items.exists():
            default_category.delete()
            print("Removed default 'Uncategorized' category")
        else:
            print("Kept 'Uncategorized' category as it has items assigned")
    except Category.DoesNotExist:
        print("No default category to remove")


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_convert_categories_to_tags'),
    ]

    operations = [
        migrations.RunPython(set_default_category, reverse_default_category),
        
        # Make category field nullable (but keep it for now for compatibility)
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='items',
                to='inventory.category',
                db_column='category_id',
                help_text='Legacy category field - will be deprecated in favor of tags'
            ),
        ),
    ]
