server {
    listen 80 default_server;
    server_name _;

    client_max_body_size 50M;

    location /static/ {
        alias /app/staticfiles/;
        access_log off;
        expires 7d;
    }
    location = /favicon.ico {
    return 301 /static/inventory/favicon.ico;
    }

    location = /favicon.svg {
        return 301 /static/inventory/favicon.svg;
    }

    location = /apple-touch-icon.png {
        return 301 /static/inventory/apple-touch-icon.png;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/run/gunicorn.sock;
    }
}
